name: Upload GoReleaser SBOMs
description: Upload GoReleaser-generated SBOMs as an artifact

author: Typist Tech Limited
branding:
  icon: 'upload'
  color: 'black'

inputs:
  name:
    description: 'Name of the artifact to upload.'
    required: true
    default: 'sboms'
  dist:
    description: 'Path to the dist folder which containing artifacts.json'
    required: true
    default: 'dist'
  sbom-suffix:
    description: 'SBOM suffix.'
    required: true
    default: '.sbom.json'
  retention-days:
    description: >
      Duration after which artifact will expire in days. 0 means using default retention.

      Minimum 1 day.
      Maximum 90 days unless changed from the repository settings page.
    required: true
    default: '0'
  compression-level:
    description: >
      The level of compression for Zlib to be applied to the artifact archive.
      The value can range from 0 to 9:
      - 0: No compression
      - 1: Best speed
      - 6: Default compression (same as GNU Gzip)
      - 9: Best compression
      Higher levels will result in better compression, but will take longer to complete.
      For large files that are not easily compressed, a value of 0 is recommended for significantly faster uploads.
    default: '6'

outputs:
  attestations:
    description: 'Pairs of SBOM and its subject'
  artifact-id:
    description: >
      A unique identifier for the artifact that was just uploaded. Empty if the artifact upload failed.

      This ID can be used as input to other APIs to download, delete or get more information about an artifact: https://docs.github.com/en/rest/actions/artifacts
runs:
  using: 'node20'
  main: 'dist/index.js'
